-- 조인
SELECT * 
FROM STUDENT;
SELECT *
FROM ENROL;

SELECT * 
FROM STUDENT
INNER JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO;

-- 조인에서는 테이블명으로 보통 별칭을 사용
SELECT S.STU_NO, STU_NAME, STU_DEPT, SUB_NAME, ENR_GRADE 
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;

