-- 학번, 이름, 학과, 시험점수 출력
-- STUDENT, ENROL
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- OUTER
-- 왼쪽 테이블에는 값이 있는데 오른쪽 테이블에 같은 값이 없는 경우
-- EX) STUDENT에는 1234라는 학번 있음, ENROL는 1234 없음
--     이럴 경우 1234학번 학생은 출력하고 ENROL테이블 컬럼은 NULL처리
-- 즉, 왼쪽테이블 데이터는 일단 모두 다 출력
SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT S LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- 오라클 조인
SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT S, ENROL E
WHERE S.STU_NO = E.STU_NO(+); -- LEFT 조인(STUDENT 테이블 기준)
-- WHERE S.STU_NO = E.STU_NO; -- INNER 조인


SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT S RIGHT JOIN ENROL E ON S.STU_NO = E.STU_NO;


SELECT 
    STU_NO, STU_NAME AS QWEQEQWEQW
FROM STUDENT
WHERE STU_GRADE = 1
UNION 
SELECT 
    STU_NO, STU_NAME AS XZXDFAF
FROM STUDENT
WHERE STU_DEPT = '기계'
ORDER BY STU_NO;


SELECT 
    STU_NO, STU_NAME, STU_DEPT,
    (SELECT AVG(STU_HEIGHT) FROM STUDENT) AS AVG_HEIGHT,
    (SELECT MAX(STU_HEIGHT) FROM STUDENT) AS AVG_HEIGHT
FROM STUDENT;






-- 키가 188인 학생은?
SELECT *
FROM STUDENT
WHERE STU_HEIGHT = 188;

-- 가장 키가 큰 학생의 이름은?
SELECT *
FROM STUDENT
WHERE STU_HEIGHT = (
    SELECT MAX(STU_HEIGHT) 
    FROM STUDENT
);

SELECT *
FROM STUDENT
WHERE STU_NO IN (20153075, 20153088);

-- WHERE STU_NO = 20153075 OR STU_NO = 20153088;

SELECT STU_NO
FROM ENROL
WHERE SUB_NO = 102;

SELECT *
FROM STUDENT
WHERE STU_NO IN (
    SELECT STU_NO
    FROM ENROL
    WHERE SUB_NO = 102
);





