-- GROUP BY

SELECT STU_DEPT, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE;

-- ROLLUP
SELECT STU_DEPT, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY ROLLUP(STU_DEPT, STU_GRADE);


SELECT STU_DEPT, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE
UNION
SELECT STU_DEPT, NULL, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT
UNION
SELECT NULL, NULL, AVG(STU_HEIGHT)
FROM STUDENT;


-- CUBE
SELECT STU_DEPT, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY CUBE(STU_DEPT, STU_GRADE)
ORDER BY STU_DEPT, STU_GRADE;


SELECT STU_DEPT, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE
UNION
SELECT STU_DEPT, NULL, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT
UNION
SELECT NULL, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_GRADE
UNION
SELECT NULL, NULL, AVG(STU_HEIGHT)
FROM STUDENT;

-- GROUPING SETS
SELECT STU_DEPT, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY GROUPING SETS(STU_DEPT, STU_GRADE);

-- UNION써서 위에랑 똑같은 결과 나오는 쿼리 작성
-- 각 학과별 평균 키 구하세요

SELECT STU_DEPT, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

-- 각 학년별 평균 키 구하세요
SELECT STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_GRADE;

--

SELECT STU_DEPT, NULL, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT
UNION ALL
SELECT NULL, STU_GRADE, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_GRADE;

-- RANK
SELECT * FROM ENROL;

SELECT stu_no, sub_no, enr_grade,
  RANK() OVER(ORDER BY enr_grade DESC) AS rnk,
  DENSE_RANK() OVER(ORDER BY enr_grade DESC) AS dense_rnk,
  ROW_NUMBER() OVER(ORDER BY enr_grade DESC) AS row_num
FROM enrol;

-- PARTITION

SELECT stu_dept, stu_name, stu_height,
  RANK() OVER(
    PARTITION BY stu_dept   -- 학과 단위로 파티션(벽)을 친다
    ORDER BY stu_height DESC
  ) AS dept_height_rnk
FROM student
WHERE stu_height IS NOT NULL;






