SELECT '20153075' AS STU_NO, '101' AS SUB_NO, 90 AS ENR_GRADE FROM DUAL
UNION ALL
SELECT '20153075' AS STU_NO, '105' AS SUB_NO, 95 AS ENR_GRADE FROM DUAL;

MERGE INTO ENROL E
USING (
    SELECT '20153075' AS STU_NO, '101' AS SUB_NO, 90 AS ENR_GRADE FROM DUAL
    UNION ALL
    SELECT '20153075' AS STU_NO, '105' AS SUB_NO, 95 AS ENR_GRADE FROM DUAL
) T -- 원래대로라면 서버같은 곳에서 받은 데이터 
ON (E.STU_NO = T.STU_NO AND E.SUB_NO = T.SUB_NO)

WHEN MATCHED THEN
    UPDATE SET E.ENR_GRADE = T.ENR_GRADE
WHEN NOT MATCHED THEN
    INSERT (SUB_NO, STU_NO, ENR_GRADE)
    VALUES (T.SUB_NO, T.STU_NO, T.ENR_GRADE);
    
COMMIT;
SELECT * FROM ENROL;
