-- 집합 연산자

-- UNION -> 중복 제거

SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_GRADE = 1
UNION
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '기계';

-- UNION ALL -> 중복된거 그대로 출력
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_GRADE = 1
UNION ALL
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '기계';


-- 집합 연산자 사용시 주의점
-- 1. 컬럼개수 통일 (아래처럼 하면 컬럼개수 달라서 에러)
SELECT 
    STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_GRADE = 1
UNION ALL
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '기계';

-- 2. 같은 위치 컬럼의 데이터타입은 같아야 함
-- 아래쿼리는 두번째 컬럼(STU_NAME, STU_HEIGHT)의 데이터 타입이 달라서 에러
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_GRADE = 1
UNION ALL
SELECT 
    STU_NO, STU_HEIGHT
FROM STUDENT
WHERE STU_DEPT = '기계';

-- 3. ORDER BY(정렬)은 맨 마지막에
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_GRADE = 1
UNION 
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '기계'
ORDER BY STU_NAME;

-- 4. 컬럼명은 위에 쿼리를 따른다.
SELECT 
    STU_NO, STU_NAME AS 학생이름
FROM STUDENT
WHERE STU_GRADE = 1
UNION 
SELECT 
    STU_NO, STU_NAME AS ㅋㅋㅋ
FROM STUDENT
WHERE STU_DEPT = '기계';

-- INTERSECT

SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_GRADE = 1
INTERSECT 
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '기계';

-- MINUS

SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_GRADE = 1
MINUS 
SELECT 
    STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '기계';

--

SELECT STU_NAME, STU_HEIGHT
FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL
UNION
SELECT '전체평균', AVG(STU_HEIGHT)
FROM STUDENT;




