-- 그룹 함수 2
-- SUM, AVG, MAX, MIN, COUNT

SELECT POSITION, SUM(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT GRADE, AVG(WEIGHT) 
FROM STU
GROUP BY GRADE; -- 학년(GRADE)별 평균 몸무게(WEIGHT)

SELECT GRADE, MAX(WEIGHT)
FROM STU
GROUP BY GRADE;

SELECT COUNT(*) -- 전체 레코드의 개수
FROM STUDENT;

SELECT COUNT(BONUS) -- BONUS가 NULL이 아닌 레코드의 수
FROM PROFESSOR;

-- STUDENT 테이블에서 각 학과의 학생 수

SELECT STU_DEPT, COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT;
--HAVING COUNT(*) >=4;

-- STEP 1. 각 학과별 학생 수
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT;

-- STEP 2. 각 학과의 남자 학생 수
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT;

-- STEP 3. 각 학과에서 남자가 2명이상인 학과명, 학생수 출력
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT
HAVING COUNT(*) >= 2;






